version: "3"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:password12!@db:5432/postgres?sslmode=disable
  db:
    image: postgres
    ports:
      - "6001:5432"
    environment:
      - POSTGRES_PASSWORD=password12!
